name: Cache
on:
  workflow_dispatch:
jobs:
  build:
    name: Build with cache job
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.x
        cache: true
        cache-dependency-path: dummy-packages.lock.json
    - name: Restore project
      run: dotnet restore
    - name: Build project
      run: dotnet build